In [17]:
import pandas as pd
corpus = pd.read_csv("shuffled_text_master.csv")

import re
bills = corpus['big_text']
new_bills = []
for bill in bills:
    new_bills.append(re.sub("\s[0-9][0-9]*", "", bill))

In [15]:
new_bills[1]

'gallego  a bill to be entitled an act relating to procedures for applications for writs of habeas corpus based on scientific evidence establishing the innocence of a criminal defendant be it enacted by the legislature of the state of texas chapter11 code of criminal procedure is amended by adding article to read as follows arta11073additional procedures for all writs  a court shall grant a convicted person relief on an application for a writ of habeas corpus if the convicted person files an application in the manner provided by article or containing sufficient specific facts indicating that scientific evidence establishing the convicted person ’s innocence is available and was not available at the time of the convicted person ’s trial because the evidence was not ascertainable through the exercise of reasonable diligence by the convicted person before the date of or during the convicted person ’s trial or the evidence was not admissible under the texas rules of evidence the scientific evidence would be admissible under the texas rules of evidence at a trial held on the date of the application and by a preponderance of the evidence norational  trier of fact could have found the applicant guilty beyond a reasonable doubt if the scientific evidence had been presented at  trial notwithstanding any other provision of this chapterif a court finds that scientific evidence exists that was not available at the time of a convicted person ’s trial the court may grant relief on the application for a writ of habeas corpus under this chapterregardless of whether the convicted person has previously filed an application under this chapternotwithstanding any other provision of this chaptera convicted person who entered a plea of guilty or nolo contendere or who made a confession or similar admission before or after conviction may submit an application for a writ of habeas corpus as provided by this section the convicting court may not deny relief on the application authorized by this subsection based solely on the applicant ’s plea confession or admission the change in law made by this act applies only to an application for a writ of habeas corpus filed on or after the effective date of this act an application for a writ of habeas corpus filed before the effective date of this act is governed by the law in effect at the time the application was filed and the former law is continued in effect for that purpose '

In [18]:
corpus

       labels                                           big_text
0           0  parker  a bill to be entitled an act relating ...
1           0  gallego  a bill to be entitled an act relating...
2           0    thompson of harris hb a noa 834 a bill to be...
3           0  bailey  a bill to be entitled an act relating ...
4           0    bucy hb a noa 2061 a bill to be entitled an ...
...       ...                                                ...
44002       0    slawson hb a noa 4386 a bill to be entitled ...
44003       1  phillips  a bill to be entitled an act relatin...
44004       0  madden  a bill to be entitled an act relating ...
44005       0  pickett  a bill to be entitled an act relating...
44006       0  neave  a bill to be entitled an act relating t...

[44007 rows x 2 columns]

In [19]:
corpus['text'] = new_bills
corpus

,labels,big_text,text
0,0,parker a bill to be entitled an act relating ...,parker a bill to be entitled an act relating ...
1,0,gallego a bill to be entitled an act relating...,gallego a bill to be entitled an act relating...
2,0,thompson of harris hb a noa 834 a bill to be...,thompson of harris hb a noa a bill to be ent...
3,0,bailey a bill to be entitled an act relating ...,bailey a bill to be entitled an act relating ...
4,0,bucy hb a noa 2061 a bill to be entitled an ...,bucy hb a noa a bill to be entitled an act r...
...,...,...,...
44002,0,slawson hb a noa 4386 a bill to be entitled ...,slawson hb a noa a bill to be entitled an ac...
44003,1,phillips a bill to be entitled an act relatin...,phillips a bill to be entitled an act relatin...
44004,0,madden a bill to be entitled an act relating ...,madden a bill to be entitled an act relating ...
44005,0,pickett a bill to be entitled an act relating...,pickett a bill to be entitled an act relating...
44006,0,neave a bill to be entitled an act relating t...,neave a bill to be entitled an act relating t...

In [21]:
corpus = corpus.drop(["big_text"], axis=1)
corpus

       labels                                               text
0           0  parker  a bill to be entitled an act relating ...
1           0  gallego  a bill to be entitled an act relating...
2           0    thompson of harris hb a noa a bill to be ent...
3           0  bailey  a bill to be entitled an act relating ...
4           0    bucy hb a noa a bill to be entitled an act r...
...       ...                                                ...
44002       0    slawson hb a noa a bill to be entitled an ac...
44003       1  phillips  a bill to be entitled an act relatin...
44004       0  madden  a bill to be entitled an act relating ...
44005       0  pickett  a bill to be entitled an act relating...
44006       0  neave  a bill to be entitled an act relating t...

[44007 rows x 2 columns]

In [22]:
corpus.to_csv("loaded_text.csv")